### ISSUE TITLE
Weird View Glitch

### ISSUE THREAD

**Issue by scorixear** [moritzruth/rustplatz#3]
Im having weird view glitches with the last Team (Unbekannt) as shown in the picture:
![grafik](https://user-images.githubusercontent.com/15715731/105104937-7ac04980-5ab3-11eb-8b82-06b89bd10c50.png)

Seems to be some sort of styling issue?
I'm using Firefox 84 with a 2560x1440 resolution. Hope this helps :)

**Comment by scorixear** [comment]
Second note: Does fix itself when resizing the Firefox windows (eg disabling and enabling full screen).
Also, where is the difference between (kein Name), (unbekannt) and (Name unbekannt)

**Comment by moritzruth** [comment]
For the team cards I am using CSS Multi-Column layouts, which are (sadly) pretty buggy. AFAIK, creating such a _masonry_ layout without CSS Columns would require complex JS for the calculations.

Because most users are using a Chromium-based browser anyway, I will not fix this.

> Also, where is the difference between (kein Name), (unbekannt) and (Name unbekannt)

- `Kein Name`: The team did not have a name the last time I asked.
- `Unbekannt`: I do not know if these players are member of a team.
- `Name unbekannt`: I did not ask/they did not answer yet.
